---
- name: Install Java 16
  become: yes
  ansible.builtin.package:
    name: openjdk-16-jre
    state: present

- name: Create server user
  ansible.builtin.user:
    name: "{{server_user}}"
    group: "{{server_group}}"
    home: /var/{{server_user}}
    shell: /bin/sh

- name: Create a disclaimer file
  ansible.builtin.copy:
    owner: "{{server_user}}"
    group: "{{server_group}}"
    dest: /var/{{server_user}}/README.md
    content: |
      # Note!
      This directory and its services are managed by https://github.com/kontza/minecraft-ansible

- name: Make sure tmux is installed
  ansible.builtin.package:
    name: tmux
    state: latest

- name: Create server instances
  ansible.builtin.include_tasks: process-instance.yml
  loop: "{{server_instances}}"
  tags:
    - always

- name: Make sure {{server_user}} owns all files
  become: yes
  ansible.builtin.file:
    path: "/var/{{server_user}}"
    owner: "{{server_user}}"
    group: "{{server_group}}"
    recurse: yes
