---
- name: Create server user
  ansible.builtin.user:
    name: "{{server_user}}"
    group: "{{server_group}}"
    home: /var/{{server_user}}
    shell: /bin/sh

- name: Make sure tmux is installed
  ansible.builtin.package:
    name: tmux
    state: latest

- name: Create server instances
  ansible.builtin.include_tasks: process-instance.yml
  loop: "{{server_instances}}"
  tags:
    - always
